services:
  etl-management-service:
    image: etl-management-service:latest
    build: etl-management-service
    container_name: etl-ems
    restart: "no"
    ports:
      - "8080:8080"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5

  extract-data-service:
    image: extract-data-service:latest
    build: extract-data-service
    container_name: etl-eds
    restart: "no"
    ports:
      - "8081:8080"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5
