spring:
  application:
    name: extract-data-service
  kafka:
    bootstrap-servers: "${SPRING_KAFKA_BOOTSTRAP_SERVERS}"
    producer:
      value-serializer: etl.engine.extract.service.messaging.CustomJsonSerializer
management:
  endpoints:
    web:
      exposure:
        include: health, info
eds:
  status-reporting:
    enabled: "${EDS_STATUS_REPORTING_ENABLED:false}"
    initial-delay: "${EDS_STATUS_REPORTING_INITIAL_DELAY}"
    fixed-rate: "${EDS_STATUS_REPORTING_FIXED_RATE}"
  topics:
    heartbeat: "${EDS_TOPICS_HEARTBEAT}"