spring:
  application:
    name: extract-data-service
management:
  endpoints:
    web:
      exposure:
        include: health, info
eds:
  status-report:
    initial-delay: 3000
    fixed-rate: 5000