spring:
  application:
    name: extract-data-service
management:
  endpoints:
    web:
      exposure:
        include: health, info
logging:
  level:
    root: "info"
    org.hibernate.orm.jdbc.bind: "trace"
    org.springframework.transaction: "debug"
    org.springframework.kafka.transaction: "debug"
    etl.engine.extract: "debug"
eds:
  ems:
    url: "${EDS_EMS_URL}"
  kafka:
    bootstrap-servers: "${EDS_KAFKA_BOOTSTRAP_SERVERS}"
    topics:
      heartbeat: "${EDS_KAFKA_TOPICS_HEARTBEAT}"
      control: "${EDS_KAFKA_TOPICS_CONTROL}"
      progress: "${EDS_KAFKA_TOPICS_PROGRESS}"
    consumer:
      group: "${spring.application.name}"
  status-reporting:
    enabled: "${EDS_STATUS_REPORTING_ENABLED:false}"
    initial-delay-ms: "${EDS_STATUS_REPORTING_INITIAL_DELAY_MS}"
    fixed-rate-ms: "${EDS_STATUS_REPORTING_FIXED_RATE_MS}"
